#!/usr/bin/env sh 


useLocalRepos() {
	sed -i 's/dl-cdn.alpinelinux.org/nexus.home.jpconsulted.com\/repository/g' /etc/apk/repositories
}

useDefaultRepos() {
	sed -i 's/nexus.home.jpconsulted.com\/repository/dl-cdn.alpinelinux.org/g' /etc/apk/repositories
}
